{% set name = "jnbv" %}
{% set version = "2022.1.29" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jnbv-{{ version }}.tar.gz
  sha256: c26427febef00b97fb340fa24e96124e3d4e3e86751346adcff4d5fa0fe101d7

build:
  number: 0
  noarch: python
  entry_points:
    - jnbv = jnbv.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - nbformat ==5.1.3
    - papermill ==2.3.3
    - python >=3.6

test:
  imports:
    - jnbv
  commands:
    - pip check
    - jnbv --help
  requires:
    - pip

about:
  home: https://gitlab.com/MAXIV-SCISW/JUPYTERHUB/jnbv
  summary: Validation of Jupyter notebooks and kernels
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jasonbrudvik
