{% set name = "jnbv" %}
{% set version = "2021.7.28.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jnbv-{{ version }}.tar.gz
  sha256: c6850172300222b3f4b43381e7a03c63a57f0620e736f5d491b13aff48009bd5

build:
  number: 0
  noarch: python
  entry_points:
    - jnbv = jnbv.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - nbformat ==5.1.3
    - papermill ==2.3.3
    - python >=3.6

test:
  imports:
    - jnbv
  commands:
    - pip check
    - jnbv --help
  requires:
    - pip

about:
  home: https://gitlab.com/MAXIV-SCISW/JUPYTERHUB/jnbv
  summary: Validation of Jupyter notebooks and kernels
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jasonbrudvik
